name: napari-intro-env

channels:
  - conda-forge
  - anaconda

dependencies:
  - python>=3.9, <3.10
  - napari==0.4.17
  - devbio-napari
  - jupyterlab
  - matplotlib
  - seaborn
  - openpyxl
  - pyrsistent
  - pip
  - pip:
      - napari-stl-exporter