# In _config.yml
title: QM Course Bio-Image Analysis with napari 2024
author: Marcelo Leomil Zoccoler
logo: biapol_logo.png
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

  # Information about where the book exists on the web
repository:
  url: https://github.com/zoccoler/QM_Course_Bio_Image_Analysis_with_napari_2024 # Online location of your book
  path_to_book: docs
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <p>
    Copyright: This work can be reused under the terms of the <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY 4.0</a> license unless mentioned otherwise.
    </p>
sphinx:
  config:
    html_show_copyright: false
